artifacts_root: artifacts


data_ingestion:  #data ingestion config
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1A5ecbptJJC2xtEA_ah2dA7ouO7P1Pzet/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

